services:
  frontend:
    build:
      context: ./Portfolio-Jhasmany-Frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3001
        - NEXT_PUBLIC_SITE_URL=http://181.114.111.21
    expose:
      - "3000"
    ports:
      - "0.0.0.0:3002:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_SITE_URL=http://181.114.111.21
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - API_URL=http://localhost:3001
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - backend
    networks:
      - portfolio-network
    restart: unless-stopped

  backend:
    build:
      context: ./Portfolio-Jhasmany-Backend
      dockerfile: Dockerfile
    expose:
      - "3001"
    ports:
      - "0.0.0.0:3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=Postgres2307***
      - DB_NAME=portfolio_db
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=7d
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=jhasmany.fernandez.dev@gmail.com
      - EMAIL_PASS=dwhx cdax xxne lrwo
      - EMAIL_FROM=jhasmany.fernandez.dev@gmail.com
      - EMAIL_FROM_NAME=Jhasmany Fernandez - Portfolio
      - FRONTEND_URL=http://localhost:3002
    depends_on:
      - postgres
    networks:
      - portfolio-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    ports:
      - "0.0.0.0:5434:5432"
    environment:
      - POSTGRES_DB=portfolio_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Postgres2307***
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-network
    restart: unless-stopped

networks:
  portfolio-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local