services:
  frontend:
    build:
      context: ./Portfolio-Jhasmany-Frontend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend
    networks:
      - portfolio-network
    restart: unless-stopped

  backend:
    build:
      context: ./Portfolio-Jhasmany-Backend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - portfolio-network
    restart: unless-stopped

networks:
  portfolio-network:
    driver: bridge

volumes:
  backend_data:
    driver: local