services:
  nginx:
    image: nginx:alpine
    ports:
      - "0.0.0.0:8000:80"
      - "0.0.0.0:8001:8080"
      - "0.0.0.0:8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - portfolio-network
    restart: unless-stopped

  frontend:
    build:
      context: ./Portfolio-Jhasmany-Frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend
    networks:
      - portfolio-network
    restart: unless-stopped

  backend:
    build:
      context: ./Portfolio-Jhasmany-Backend
      dockerfile: Dockerfile
    expose:
      - "3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - portfolio-network
    restart: unless-stopped

networks:
  portfolio-network:
    driver: bridge

volumes:
  backend_data:
    driver: local